Add bobcat 2023.2/candidate channels
openstack-charmers/charmed-openstack-info pull request #39
Opened 2023-10-07 10:49 UTC by ajkavanagh

Add the bobcat 2023.2 channes for the OpenStack charms. The recipe is to
push to /candidate for SQA to consume prior to releasing to stable. Bug
fixes during the testing period will therefore be pushed to /candidate
to assist with simplified testing of any fixes.

The charmcraft 2.2/stable channel has been selected for the recipes as
that is the latest stable channel availble for long term building of the
bobcat charms.

Bases 22.04 and 23.10 have been selected to support jammy and mantic.

2023-10-11 20:06 UTC, freyes requested changes

2023-10-11 20:06 UTC, freyes commented on charmed_openstack_info/data/lp-builder-config/openstack.yaml
> +        charmcraft: "2.2/stable"
Blocking until https://github.com/canonical/craft-providers/pull/330 gets available in a release, or we agree something different.

2023-10-12 13:12 UTC, fnordahl commented on charmed_openstack_info/data/lp-builder-config/openstack.yaml
>    # - name: OpenStack Neutron Dynamic Routing Charm
A rebase is needed after #40 merged, it provided a commented out section for the stable channel, which I guess can be uncommented as part of this PR

2023-10-24 19:51 UTC, freyes commented
Blocked by https://github.com/canonical/charmcraft/pull/1354

2023-10-26 16:15 UTC, freyes approved these changes

2023-10-26 16:24 UTC, merged